### PR TITLE
rename source in logs to librato_source

### PR DESCRIPTION
**Pull request by jmervine**
Renaming `source` key in logs to `librato_source` for better indexing and faster searching.

@joshuatobin @reidmix

### CODE REVIEW

**Comment by joshuatobin** [comment]
@jmervine Change looks good, however the tests seem to be failing during the bundle. Didn't dig more more than that.

**Comment by freeformz** [comment]
FWIW: `source` means something to Librato and could possibly break metrics if removed. AFAIK `librato_source` doesn't mean anything to librato. Have they made that change recently?

**Comment by reidmix** [comment]
The parameter name isn't changing on it's request to librato, the way I read it is that it's logging `source` as `librato_source`.  Is that right?

**Comment by joshuatobin** [comment]
@freeformz The original intent here was to map "source" to "librato_source" for better splunking (source collides with a splunk keyword). Would this change break l2met parsing?

**Comment by freeformz** [comment]
Oh IC what's going on. Nevermind, move along here, my mistake.

**Comment by jmervine** [comment]
@joshuatobin @reidmix tests now passing

**Comment by jmervine** [comment]
@heroku/sre `ping`

**Comment by joshuatobin** [comment]
:+1:

**Comment by reidmix** [comment]
👍

**Pull request merged**
