### PR TITLE
making config.ru style puma app

### PR DESCRIPTION
**Pull request by jmervine**
I'm updating app init to be a puma based rack app to allow for setting multiple workers. Additionally, I added pry for debugging and troubleshooting.

cc @reidmix @joshuatobin

### CODE REVIEW

**Comment by joshuatobin** [comment]
👍 Looks good to me. Also would like to see what @reidmix thinks.

**Comment by jmervine** [comment]
Here you can see the response time graph smooth out with this change, marked by `v9`...

screen shot 2017-01-04 at 2 58 04 pm

**Comment by reidmix** [comment]
This is cool.

Because I'm curious:
It was using Puma before, but it wasn't a Rack app before, correct?
Did it smooth out simply because Puma is a rack app or because it has more threads?

**Comment by reidmix** [comment]
I was more interested in the why because I've never looked at it from this PR's perspective. :D

**Pull request merged**
