### PR TITLE
Bump ruby to 2.4.0

### PR DESCRIPTION
**Pull request by joshuatobin**
CC: @heroku/sre

### CODE REVIEW

**Comment by jmervine** [comment]
@joshuatobin rebased this with master to test PR apps

**Comment by jblaine** [comment]
Any chance of this being merged?

**Comment by jmervine** [comment]
@jblaine I'm in the middle of debugging something with the last merge. But I'll rehash this after.

**Comment by jmervine** [comment]
👍

**Comment by jmervine** [comment]
@CobyR This failed badly and I reverted it. I'm going to close this, as I think we'll EOL umpire by moving to librato alerts before actually getting to resolution on this.

**Pull request closed without merging**
